"""empty message

Revision ID: 158580316a50
Revises: 495ffff22d4c
Create Date: 2022-07-19 20:08:07.742469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '158580316a50'
down_revision = '495ffff22d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_entry_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_sl_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_liq_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_leverage', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_qty', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_position_margin', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_risk_amount', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_be_rw_config', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_profit_rw_config', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_ep_sl_gap', sa.Float(), nullable=True))
    op.drop_column('tv_alert', 'exg_profit_rw_config')
    op.drop_column('tv_alert', 'exg_risk_amount')
    op.drop_column('tv_alert', 'exg_init_ep_sl_gap')
    op.drop_column('tv_alert', 'exg_bev_rw_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('exg_bev_rw_config', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('exg_init_ep_sl_gap', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('exg_risk_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('exg_profit_rw_config', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'my_init_ep_sl_gap')
    op.drop_column('tv_alert', 'my_profit_rw_config')
    op.drop_column('tv_alert', 'my_be_rw_config')
    op.drop_column('tv_alert', 'my_risk_amount')
    op.drop_column('tv_alert', 'my_position_margin')
    op.drop_column('tv_alert', 'my_qty')
    op.drop_column('tv_alert', 'my_leverage')
    op.drop_column('tv_alert', 'my_liq_price')
    op.drop_column('tv_alert', 'my_init_sl_price')
    op.drop_column('tv_alert', 'my_init_entry_price')
    # ### end Alembic commands ###
