"""empty message

Revision ID: 18b80fb1c366
Revises: 9e2d1afa9437
Create Date: 2022-08-26 14:03:18.122255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18b80fb1c366'
down_revision = '9e2d1afa9437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_pnl_config', sa.Column('loss_perc_threshold', sa.Float(), nullable=True))
    op.add_column('my_pnl_config', sa.Column('profit_amount_threshold', sa.Float(), nullable=True))
    op.drop_column('my_pnl_config', 'profit_threshold')
    op.drop_column('my_pnl_config', 'loss_threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_pnl_config', sa.Column('loss_threshold', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('my_pnl_config', sa.Column('profit_threshold', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('my_pnl_config', 'profit_amount_threshold')
    op.drop_column('my_pnl_config', 'loss_perc_threshold')
    # ### end Alembic commands ###
