"""empty message

Revision ID: 241b4844203b
Revises: 158580316a50
Create Date: 2022-07-19 21:48:36.031152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241b4844203b'
down_revision = '158580316a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_executed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'my_executed_at')
    # ### end Alembic commands ###
