"""empty message

Revision ID: 3abf5ea48238
Revises: d33d999b4260
Create Date: 2022-07-25 03:16:52.917847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3abf5ea48238'
down_revision = 'd33d999b4260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'exg_init_sl_mark_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('exg_init_sl_mark_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
