"""empty message

Revision ID: 495ffff22d4c
Revises: 559a2467ade4
Create Date: 2022-07-19 18:17:43.857746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495ffff22d4c'
down_revision = '559a2467ade4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('exg_executed_at', sa.DateTime(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_order_id', sa.String(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_stop_order_id', sa.String(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_is_isolated', sa.String(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_qty', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_risk_amount', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_avail_balance', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_pos_margin', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_bev_rw_config', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_profit_rw_config', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_init_entry_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_init_sl_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_init_ep_sl_gap', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_liq_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_leverage', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_trailed_sl_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_trailed_profit_sl_counter', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_passed_bev_target', sa.Boolean(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_passed_profit_target', sa.Boolean(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_close_trigger_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_close_at', sa.DateTime(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_close_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'exg_close_amount')
    op.drop_column('tv_alert', 'exg_close_at')
    op.drop_column('tv_alert', 'exg_close_trigger_price')
    op.drop_column('tv_alert', 'exg_passed_profit_target')
    op.drop_column('tv_alert', 'exg_passed_bev_target')
    op.drop_column('tv_alert', 'exg_trailed_profit_sl_counter')
    op.drop_column('tv_alert', 'exg_trailed_sl_price')
    op.drop_column('tv_alert', 'exg_leverage')
    op.drop_column('tv_alert', 'exg_liq_price')
    op.drop_column('tv_alert', 'exg_init_ep_sl_gap')
    op.drop_column('tv_alert', 'exg_init_sl_price')
    op.drop_column('tv_alert', 'exg_init_entry_price')
    op.drop_column('tv_alert', 'exg_profit_rw_config')
    op.drop_column('tv_alert', 'exg_bev_rw_config')
    op.drop_column('tv_alert', 'exg_pos_margin')
    op.drop_column('tv_alert', 'exg_avail_balance')
    op.drop_column('tv_alert', 'exg_risk_amount')
    op.drop_column('tv_alert', 'exg_qty')
    op.drop_column('tv_alert', 'exg_is_isolated')
    op.drop_column('tv_alert', 'exg_stop_order_id')
    op.drop_column('tv_alert', 'exg_order_id')
    op.drop_column('tv_alert', 'exg_executed_at')
    # ### end Alembic commands ###
