"""empty message

Revision ID: 559a2467ade4
Revises: 
Create Date: 2022-07-18 20:22:43.468771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559a2467ade4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('command', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=7), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_alert')
    # ### end Alembic commands ###
