"""empty message

Revision ID: 5896343fd385
Revises: 1631ba82c7c5
Create Date: 2022-08-24 17:20:25.223057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5896343fd385'
down_revision = '1631ba82c7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_balance')
    # ### end Alembic commands ###
