"""empty message

Revision ID: 58dadcea4b61
Revises: 90210524639f
Create Date: 2022-07-22 16:53:26.711653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58dadcea4b61'
down_revision = '90210524639f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_order_book_price_tier', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_max_slippage_price_tier_config', sa.Float(), nullable=True))
    op.drop_column('tv_alert', 'my_init_possible_slippage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_possible_slippage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'my_max_slippage_price_tier_config')
    op.drop_column('tv_alert', 'my_init_order_book_price_tier')
    # ### end Alembic commands ###
