"""empty message

Revision ID: 68972daae827
Revises: fd96d1afac04
Create Date: 2022-08-03 00:21:01.742553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68972daae827'
down_revision = 'fd96d1afac04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('symbol_', sa.String(length=50), nullable=True))
    op.drop_column('tv_alert', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'symbol_')
    # ### end Alembic commands ###
