"""empty message

Revision ID: 7127bb0d3864
Revises: f308bda1b7d8
Create Date: 2022-07-25 02:21:33.773372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7127bb0d3864'
down_revision = 'f308bda1b7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_slippage_counter', sa.Float(), nullable=True))
    op.drop_column('tv_alert', 'my_init_order_book_price_tier')
    op.drop_column('tv_alert', 'my_init_ep_mark_sl_gap')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_ep_mark_sl_gap', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_order_book_price_tier', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'my_slippage_counter')
    # ### end Alembic commands ###
