"""empty message

Revision ID: 82826dd9d686
Revises: 58dadcea4b61
Create Date: 2022-07-22 16:54:03.965954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82826dd9d686'
down_revision = '58dadcea4b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_max_slippage_counter_config', sa.Float(), nullable=True))
    op.drop_column('tv_alert', 'my_max_slippage_price_tier_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_max_slippage_price_tier_config', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'my_max_slippage_counter_config')
    # ### end Alembic commands ###
