"""empty message

Revision ID: 90210524639f
Revises: 966b27c9b917
Create Date: 2022-07-22 16:35:15.860687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90210524639f'
down_revision = '966b27c9b917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_last_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_best_order_book_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_possible_slippage', sa.Float(), nullable=True))
    op.drop_column('tv_alert', 'my_init_entry_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_entry_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'my_init_possible_slippage')
    op.drop_column('tv_alert', 'my_init_best_order_book_price')
    op.drop_column('tv_alert', 'my_init_last_price')
    # ### end Alembic commands ###
