"""empty message

Revision ID: d33d999b4260
Revises: fdb6fb7ed35c
Create Date: 2022-07-25 02:56:42.262861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33d999b4260'
down_revision = 'fdb6fb7ed35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_best_ord_book_ep_sl_gap', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'my_init_best_ord_book_ep_sl_gap')
    # ### end Alembic commands ###
