"""empty message

Revision ID: f308bda1b7d8
Revises: 82826dd9d686
Create Date: 2022-07-22 23:27:49.095937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f308bda1b7d8'
down_revision = '82826dd9d686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_init_entry_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_sl_mark_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_be_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_profit_target', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_liq_mark_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_sl_vs_liq_gap_perc', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_mark_sl_vs_liq_gap_perc', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_max_leverage_config', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_ep_sl_gap', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_ep_mark_sl_gap', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_init_sl_last_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_init_sl_mark_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_liq_mark_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_trailed_entry_price', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_trailed_profit_target', sa.Float(), nullable=True))
    op.drop_column('tv_alert', 'my_liq_price')
    op.drop_column('tv_alert', 'exg_liq_price')
    op.drop_column('tv_alert', 'my_init_last_price')
    op.drop_column('tv_alert', 'exg_init_sl_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('exg_init_sl_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('my_init_last_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('exg_liq_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tv_alert', sa.Column('my_liq_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tv_alert', 'exg_trailed_profit_target')
    op.drop_column('tv_alert', 'exg_trailed_entry_price')
    op.drop_column('tv_alert', 'exg_liq_mark_price')
    op.drop_column('tv_alert', 'exg_init_sl_mark_price')
    op.drop_column('tv_alert', 'exg_init_sl_last_price')
    op.drop_column('tv_alert', 'my_init_ep_mark_sl_gap')
    op.drop_column('tv_alert', 'my_init_ep_sl_gap')
    op.drop_column('tv_alert', 'my_max_leverage_config')
    op.drop_column('tv_alert', 'my_mark_sl_vs_liq_gap_perc')
    op.drop_column('tv_alert', 'my_sl_vs_liq_gap_perc')
    op.drop_column('tv_alert', 'my_liq_mark_price')
    op.drop_column('tv_alert', 'my_init_profit_target')
    op.drop_column('tv_alert', 'my_init_be_price')
    op.drop_column('tv_alert', 'my_init_sl_mark_price')
    op.drop_column('tv_alert', 'my_init_entry_price')
    # ### end Alembic commands ###
