"""empty message

Revision ID: f34153976e4c
Revises: 241b4844203b
Create Date: 2022-07-22 13:11:48.096365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34153976e4c'
down_revision = '241b4844203b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('exg_init_ep_sl_gap', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'exg_init_ep_sl_gap')
    # ### end Alembic commands ###
