"""empty message

Revision ID: fd96d1afac04
Revises: 279e98bf5b0b
Create Date: 2022-08-02 14:06:54.337955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd96d1afac04'
down_revision = '279e98bf5b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('my_expected_risk_amount', sa.Float(), nullable=True))
    op.add_column('tv_alert', sa.Column('exg_risk_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'exg_risk_amount')
    op.drop_column('tv_alert', 'my_expected_risk_amount')
    # ### end Alembic commands ###
