"""empty message

Revision ID: fdb6fb7ed35c
Revises: 7127bb0d3864
Create Date: 2022-07-25 02:23:37.187152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdb6fb7ed35c'
down_revision = '7127bb0d3864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_alert', 'exg_close_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_alert', sa.Column('exg_close_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
